### ISSUE TITLE
keep_alive throws exception after losing connection

### ISSUE THREAD

**Issue by automat115** [open-homeautomation/pknx#15]
I have a connection to a KNX IP router with a keep alive thread running in the background. It sends heartbeats for a while, then finds no active connection and at the next heartbeat, throws an exception as seen below.

```
DEBUG:root:Heartbeat: Send connection state request
DEBUG:root:Heartbeat: Successful
DEBUG:root:Heartbeat: Send connection state request
DEBUG:root:Heartbeat: Successful
DEBUG:root:Heartbeat: Send connection state request
ERROR:root:Heartbeat: Response No active connection found for Channel:5 
DEBUG:root:Heartbeat: Send connection state request
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/.../knxip/ip.py", line 272, in keepalive
    self.check_connection_state()
  File "/Users/.../knxip/ip.py", line 436, in check_connection_state
    self.control_socket.sendto(bytes(frame.to_frame()),
  File "/Users/.../knxip/ip.py", line 58, in to_frame
    return bytearray(self.header() + self.body)
TypeError: can only concatenate list (not "bytes") to list
```

**Comment by daBONDi** [comment]
What KNX IP Router you use?

**Comment by daBONDi** [comment]
Possible that you send me a Wireshark Dump on the Host using the libary when this happening, so i can look on the KNX Network Packet?

**Comment by automat115** [comment]
Here's the wireshark dump of the last few packets. the failure should be happening here
[packetdump.txt](https://github.com/open-homeautomation/pknx/files/582883/packetdump.txt)

**Comment by automat115** [comment]
Using this Schneider router http://www.schneider-electric.com/en/download/document/MTN680329_HW_2014_46_EN/

Here's a dump with more packets and working heartbeats
[packetdumplg.txt](https://github.com/open-homeautomation/pknx/files/582895/packetdumplg.txt)

**Comment by daBONDi** [comment]
Can you send me a wireshark dump?
Wireshark Save as -> pcapng or something
need to see the payload itself for the channel id stuff

that what you send me looks ok on the first peek, you use the lib with Home Assistant?
