### ISSUE TITLE
Reconnection goes it perpetual failure after reconnect attempt fails

### ISSUE THREAD

**Issue by elupus** [open-homeautomation/pknx#19]
I've got a problem with knxip where the connection to the router temporarily goes down. This likely triggers the disconnect(), connect() pattern where the connect() request likely fails. After which i get these exceptions continuously logged:

```
Jun 16 13:41:07 hass hass[50235]: 2017-06-16 13:41:07 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.uttag_gastrum fails
Jun 16 13:41:07 hass hass[50235]: Traceback (most recent call last):
Jun 16 13:41:07 hass hass[50235]:   File "/home/homeassistant/env/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 224, in async_update_ha_state
Jun 16 13:41:07 hass hass[50235]:     yield from self.hass.async_add_job(self.update)
Jun 16 13:41:07 hass hass[50235]:   File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
Jun 16 13:41:07 hass hass[50235]:     yield self  # This tells Task to wait for completion.
Jun 16 13:41:07 hass hass[50235]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
Jun 16 13:41:07 hass hass[50235]:     future.result()
Jun 16 13:41:07 hass hass[50235]:   File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
Jun 16 13:41:07 hass hass[50235]:     raise self._exception
Jun 16 13:41:07 hass hass[50235]:   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Jun 16 13:41:07 hass hass[50235]:     result = self.fn(*self.args, **self.kwargs)
Jun 16 13:41:07 hass hass[50235]:   File "/home/homeassistant/env/lib/python3.5/site-packages/homeassistant/components/knx.py", line 192, in update
Jun 16 13:41:07 hass hass[50235]:     self.state_address, use_cache=self.cache)
Jun 16 13:41:07 hass hass[50235]:   File "/home/homeassistant/.homeassistant/deps/knxip/ip.py", line 557, in group_read
Jun 16 13:41:07 hass hass[50235]:     self.send_tunnelling_request(cemi)
Jun 16 13:41:07 hass hass[50235]:   File "/home/homeassistant/.homeassistant/deps/knxip/ip.py", line 539, in send_tunnelling_request
Jun 16 13:41:07 hass hass[50235]:     self.disconnect()
Jun 16 13:41:07 hass hass[50235]:   File "/home/homeassistant/.homeassistant/deps/knxip/ip.py", line 387, in disconnect
Jun 16 13:41:07 hass hass[50235]:     frame.body = self.hpai_body()
Jun 16 13:41:07 hass hass[50235]:   File "/home/homeassistant/.homeassistant/deps/knxip/ip.py", line 497, in hpai_body
Jun 16 13:41:07 hass hass[50235]:     body.extend(ip_to_array(self.control_socket.getsockname()[0]))
Jun 16 13:41:07 hass hass[50235]: AttributeError: 'NoneType' object has no attribute 'getsockname'

```

**Comment by elupus** [comment]
By the looks of things. the disconnect() function should reset self.channel, but also perhaps check for an existing socket.

**Comment by open-homeautomation** [comment]
THe pull request has been merged. Please test with version 0.4

**Comment by elupus** [comment]
Thanx. It seems to be mostly fixed. I've managed to get it into an impossible state thou. I think there is an issue with "threads" in home assistant that trigger strange things. 

When tunnel goes down, hass will queue up multiple update() requests and group address reads since the connect takes some time. Hass is normally single threaded with async event loop. But since the knx component in hass is not async it will use it's legacy compatibility wrapper where it will spawn threads to run commands. 

I'm suspecting that the calls into socket.write/recv will be blocking, causing python to reschedule a new thread, which ends up calling into knxip component while the knxip component is blocking internally already. This get's the component in an unexpected inconsistent state.

See for example: https://github.com/home-assistant/home-assistant/pull/3188 where they solved that issue for modbus. Must say that one looks a bit overkill, a simple mutex around calls into knxip from hass should be enough.

**Comment by elupus** [comment]
Many components use: threading.Lock() and with clauses to protect. I'd say the issue in hass not knxip thou since knxip doesn't claim to be threadsafe. So i'll see if I can solve it there.

**Comment by open-homeautomation** [comment]
I'm also having problems in HASS as knxip isn't thread-save (not only on reconnect). I think some locking is needed in knxip to serialize read/write commands. I think the easiest way is to implement locking on the groupread and groupwrite methods. I will look into this.

**Comment by open-homeautomation** [comment]
@elupus I pushed an update with locking on read/write operations. Please check this.

**Comment by elupus** [comment]
Better with the locking. I still get strange situations when i stop knxd while hass is connected. I don't understand how this occurs :( this is not the exact v5 release since that doesn't exist in the the pip repo's, and i've not figured out how to run an explicit version for use with hass yet.)

```
Jul 08 21:32:32 hass hass[36968]: ERROR:root:KNX/IP gateway did not respond to connect request
Jul 08 21:32:34 hass hass[36968]: ERROR:homeassistant.helpers.entity:Update for light.spegelbelysning_badrum fails
Jul 08 21:32:34 hass hass[36968]: Traceback (most recent call last):
Jul 08 21:32:34 hass hass[36968]:   File "/home/homeassistant/env/lib/python3.5/site-packages/homeassistant/helpers/entity
Jul 08 21:32:34 hass hass[36968]:     yield from self.hass.async_add_job(self.update)
Jul 08 21:32:34 hass hass[36968]:   File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
Jul 08 21:32:34 hass hass[36968]:     yield self  # This tells Task to wait for completion.
Jul 08 21:32:34 hass hass[36968]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
Jul 08 21:32:34 hass hass[36968]:     future.result()
Jul 08 21:32:34 hass hass[36968]:   File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
Jul 08 21:32:34 hass hass[36968]:     raise self._exception
Jul 08 21:32:34 hass hass[36968]:   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Jul 08 21:32:34 hass hass[36968]:     result = self.fn(*self.args, **self.kwargs)
Jul 08 21:32:34 hass hass[36968]:   File "/home/homeassistant/env/lib/python3.5/site-packages/homeassistant/components/knx
Jul 08 21:32:34 hass hass[36968]:     self.state_address, use_cache=self.cache)
Jul 08 21:32:34 hass hass[36968]:   File "/home/homeassistant/.homeassistant/deps/knxip/ip.py", line 560, in group_read
Jul 08 21:32:34 hass hass[36968]:     self.send_tunnelling_request(cemi)
Jul 08 21:32:34 hass hass[36968]:   File "/home/homeassistant/.homeassistant/deps/knxip/ip.py", line 540, in send_tunnelli
Jul 08 21:32:34 hass hass[36968]:     self.disconnect()
Jul 08 21:32:34 hass hass[36968]:   File "/home/homeassistant/.homeassistant/deps/knxip/ip.py", line 388, in disconnect
Jul 08 21:32:34 hass hass[36968]:     frame.body = self.hpai_body()
Jul 08 21:32:34 hass hass[36968]:   File "/home/homeassistant/.homeassistant/deps/knxip/ip.py", line 498, in hpai_body
Jul 08 21:32:34 hass hass[36968]:     body.extend(ip_to_array(self.control_socket.getsockname()[0]))
Jul 08 21:32:34 hass hass[36968]: AttributeError: 'NoneType' object has no attribute 'getsockname'

```

**Comment by elupus** [comment]
Scratch this comment. I had lost my changes since v3.3 so it was the old issue.

**Comment by elupus** [comment]
The locking seem to have resolved some the issues. Still something odd going on. After i restart knxd hass keeps on logging:

```
Jul 08 21:53:34 hass hass[37418]: INFO:root:Data server already running, not starting again
Jul 08 21:53:37 hass hass[37418]: INFO:root:Data server already running, not starting again
Jul 08 21:53:40 hass hass[37418]: INFO:root:Data server already running, not starting again
Jul 08 21:53:43 hass hass[37418]: INFO:root:Data server already running, not starting again
Jul 08 21:53:46 hass hass[37418]: INFO:root:Data server already running, not starting again
Jul 08 21:53:49 hass hass[37418]: INFO:root:Data server already running, not starting again
Jul 08 21:53:52 hass hass[37418]: INFO:root:Data server already running, not starting again
Jul 08 21:53:53 hass hass[37418]: WARNING:homeassistant.components.light:Updating knx light took longer than the scheduled update interval 0:00:30
```

I'm not sure how it gets into that state. It sort of looks like it's not connected, but fails the reconnect silently.

Ps. I started playing around with a asynco version, with multicast instead of tunneling here: https://github.com/elupus/pknx/tree/device I'm open for comments on it
